# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go generate ./...
    - go test ./... -coverprofile dist/main-cover.out -v
    - go tool cover -html=dist/main-cover.out -o dist/dist-coverage.html
    - cp dist/dist-coverage.html coverage/index.html

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
archive:
  name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
scoop:
  commit_author:
    name: marcelocorreia
    email: marcelo@correia.io
brew:
  commit_author:
    name: marcelocorreia
    email: marcelo@correia.io
github_urls:
  download: https://github.com/marcelocorreia/{{ .ProjectName }}
